@startuml

title Raytracer - Initial Architecture (Parser & Help)

class Parser {
    - _displayHelp : bool
    - parseArguments(ac : int, av : char**) : void
    + Parser(ac : int, av : char**)
    + shouldDisplayHelp() : bool
}

class Help {
    + printHelp() : int
}

class TEST {
}

Parser --> Help : uses

@enduml