namespace Math {
	class Point3D {
		+Point3D()
		+Point3D(double x, double y, double z)
		+~Point3D()
		+operator+(const Vector3D& vec) : Point3D {query}
		+operator-(const Point3D& other) : Vector3D {query}
		+x : double
		+y : double
		+z : double
	}

	class Vector3D {
		+Vector3D(double x, double y, double z)
		+~Vector3D()
		+normalize() : Vector3D {query}
		+operator*(double scalar) : Vector3D {query}
		+operator+(const Vector3D& other) : Vector3D {query}
		+operator-(const Vector3D& other) : Vector3D {query}
		+operator/(double scalar) : Vector3D {query}
		+dot(const Vector3D& other) : double {query}
		+length() : double {query}
		+x : double
		+y : double
		+z : double
	}
}

@enduml
