name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

env:
    MIRROR_URL: git@github.com:EpitechPGE2-2025/G-OOP-400-RUN-4-1-raytracer-5.git

jobs:
  build-test-uml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make g++ default-jre graphviz libcriterion-dev libconfig++-dev
          pip install hpp2plantuml

      - name: Build
        run: make re

      - name: Build tests
        run: make tests_run

      #- name: Run tests
      #  run: ./tests_run

      - name: Generate UML diagram from headers
        run: |
          hpp2plantuml -i "src/**/*.hpp" -o docs/uml/diagram.puml

      - name: Generate UML image
        run: |
          curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
          java -jar plantuml.jar docs/uml/diagram.puml

      - name: Commit UML if changed
        if: github.actor != 'github-actions[bot]'
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@bot.com"
          git add docs/uml/diagram.puml docs/uml/diagram.png
          git diff --cached --quiet || git commit -m "update UML diagram"
          git push

  push-to-mirror:
    runs-on: ubuntu-latest
    needs: build-test-uml
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror repo
        env:
          SSH_PRIVATE_KEY_B64: ${{ secrets.SSH_PRIVATE_KEY_B64 }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_ed25519
          head -n 1 ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git remote add mirror $MIRROR_URL
          GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519" git push mirror main --force
